using System;
using System.Collections.Generic;

namespace McGillWebAPI.Model
{
    public partial class SectionD
    {
        public int EmploymentAppId { get; set; }
        public string EmployerFirst { get; set; }
        public string EmployerSecond { get; set; }
        public string EmployerThird { get; set; }
        public string TelephoneFirst { get; set; }
        public string TelephoneSecond { get; set; }
        public string TelephoneThird { get; set; }
        public string AddressFirst { get; set; }
        public string AddressSecond { get; set; }
        public string AddressThird { get; set; }
        public string DescriptionFirst { get; set; }
        public string DescriptionSecond { get; set; }
        public string DescriptionThird { get; set; }
        public string StartMonthFirst { get; set; }
        public string StartMonthSecond { get; set; }
        public string StartMonthThird { get; set; }
        public string StartYearFirst { get; set; }
        public string StartYearSecond { get; set; }
        public string StartYearThird { get; set; }
        public string WageStartFirst { get; set; }
        public string WageStartSecond { get; set; }
        public string WageStartThird { get; set; }
        public string WageStartUnitFirst { get; set; }
        public string WageStartUnitSecond { get; set; }
        public string WageStartUnitThird { get; set; }
        public string PositionFirst { get; set; }
        public string PositionSecond { get; set; }
        public string PositionThird { get; set; }
        public string DepartmentFirst { get; set; }
        public string DepartmentSecond { get; set; }
        public string DepartmentThird { get; set; }
        public string EndMonthFirst { get; set; }
        public string EndMonthSecond { get; set; }
        public string EndMonthThird { get; set; }
        public string EndYearFirst { get; set; }
        public string EndYearSecond { get; set; }
        public string EndYearThird { get; set; }
        public string WageEndFirst { get; set; }
        public string WageEndSecond { get; set; }
        public string WageEndThird { get; set; }
        public string WageEndUnitFirst { get; set; }
        public string WageEndUnitSecond { get; set; }
        public string WageEndUnitThird { get; set; }
        public string RaiseMonthFirst { get; set; }
        public string RaiseMonthSecond { get; set; }
        public string RaiseMonthThird { get; set; }
        public string RaiseYearFirst { get; set; }
        public string RaiseYearSecond { get; set; }
        public string RaiseYearThird { get; set; }
        public string AdditionWageFirst { get; set; }
        public string AdditionWageSecond { get; set; }
        public string AdditionWageThird { get; set; }
        public string AdditionUnitFirst { get; set; }
        public string AdditionUnitSecond { get; set; }
        public string AdditionUnitThird { get; set; }
        public string AdditionExplainFirst { get; set; }
        public string AdditionExplainSecond { get; set; }
        public string AdditionExplainThird { get; set; }
        public int? HealthCareFirst { get; set; }
        public int? HealthCareSecond { get; set; }
        public int? HealthCareThird { get; set; }
        public string OtherBenefitsFirst { get; set; }
        public string OtherBenefitsSecond { get; set; }
        public string OtherBenefitsThird { get; set; }
        public string WorkFirst { get; set; }
        public string WorkSecond { get; set; }
        public string WorkThird { get; set; }
        public string WorkHoursFirst { get; set; }
        public string WorkHoursSecond { get; set; }
        public string WorkHoursThird { get; set; }
        public string ObtainFirst { get; set; }
        public string ObtainSecond { get; set; }
        public string ObtainThird { get; set; }
        public string SupervisorFirst { get; set; }
        public string SupervisorSecond { get; set; }
        public string SupervisorThird { get; set; }
        public string ReferencesFirst { get; set; }
        public string ReferencesSecond { get; set; }
        public string ReferencesThird { get; set; }
        public string DutiesFirst { get; set; }
        public string DutiesSecond { get; set; }
        public string DutiesThird { get; set; }
        public string ResponsibilityFirst { get; set; }
        public string ResponsibilitySecond { get; set; }
        public string ResponsibilityThird { get; set; }
        public string LeavingFirst { get; set; }
        public string LeavingSecond { get; set; }
        public string LeavingThird { get; set; }
        public string OtherCompanyOne { get; set; }
        public string OtherCompanyTwo { get; set; }
        public string OtherCompanyThree { get; set; }
        public string OtherStartMonthOne { get; set; }
        public string OtherStartMonthTwo { get; set; }
        public string OtherStartMonthThree { get; set; }
        public string OtherStartYearOne { get; set; }
        public string OtherStartYearTwo { get; set; }
        public string OtherStartYearThree { get; set; }
        public string OtherHoursOne { get; set; }
        public string OtherHoursTwo { get; set; }
        public string OtherHoursThree { get; set; }
        public string OtherPositionOne { get; set; }
        public string OtherPositionTwo { get; set; }
        public string OtherPositionThree { get; set; }
        public string OtherWageOne { get; set; }
        public string OtherWageTwo { get; set; }
        public string OtherWageThree { get; set; }
        public string OtherLeavingOne { get; set; }
        public string OtherLeavingTwo { get; set; }
        public string OtherLeavingThree { get; set; }
        public string OtherAddressOne { get; set; }
        public string OtherAddressTwo { get; set; }
        public string OtherAddressThree { get; set; }
        public string OtherEndMonthOne { get; set; }
        public string OtherEndMonthTwo { get; set; }
        public string OtherEndMonthThree { get; set; }
        public string OtherEndYearOne { get; set; }
        public string OtherEndYearTwo { get; set; }
        public string OtherEndYearThree { get; set; }
        public string OtherSupervisorOne { get; set; }
        public string OtherSupervisorTwo { get; set; }
        public string OtherSupervisorThree { get; set; }
        public string OtherUnitOne { get; set; }
        public string OtherUnitTwo { get; set; }
        public string OtherUnitThree { get; set; }
        public string UnemployedStartMonthOne { get; set; }
        public string UnemployedStartMonthTwo { get; set; }
        public string UnemployedStartMonthThree { get; set; }
        public string UnemployedStartYearOne { get; set; }
        public string UnemployedStartYearTwo { get; set; }
        public string UnemployedStartYearThree { get; set; }
        public string UnemployedEndMonthOne { get; set; }
        public string UnemployedEndMonthTwo { get; set; }
        public string UnemployedEndMonthThree { get; set; }
        public string UnemployedEndYearOne { get; set; }
        public string UnemployedEndYearTwo { get; set; }
        public string UnemployedEndYearThree { get; set; }
        public string UnemployedWeeksOne { get; set; }
        public string UnemployedWeeksTwo { get; set; }
        public string UnemployedWeeksThree { get; set; }
        public string UnemployedTimeOne { get; set; }
        public string UnemployedTimeTwo { get; set; }
        public string UnemployedTimeThree { get; set; }
        public string UnemployedFinanceOne { get; set; }
        public string UnemployedFinanceTwo { get; set; }
        public string UnemployedFinanceThree { get; set; }

        public virtual EmploymentApp EmploymentApp { get; set; }
    }
}
